// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sample.proto

package sample

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// This is just a guid type placeholder
type TestMessage struct {
	Value                string      `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	SubValue             *SubMessage `protobuf:"bytes,2,opt,name=sub_value,json=subValue,proto3" json:"sub_value,omitempty"`
	MyData               []byte      `protobuf:"bytes,3,opt,name=my_data,json=myData,proto3" json:"my_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TestMessage) Reset()         { *m = TestMessage{} }
func (m *TestMessage) String() string { return proto.CompactTextString(m) }
func (*TestMessage) ProtoMessage()    {}
func (*TestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_2141552de9bf11d0, []int{0}
}

func (m *TestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestMessage.Unmarshal(m, b)
}
func (m *TestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestMessage.Marshal(b, m, deterministic)
}
func (m *TestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestMessage.Merge(m, src)
}
func (m *TestMessage) XXX_Size() int {
	return xxx_messageInfo_TestMessage.Size(m)
}
func (m *TestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TestMessage proto.InternalMessageInfo

func (m *TestMessage) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *TestMessage) GetSubValue() *SubMessage {
	if m != nil {
		return m.SubValue
	}
	return nil
}

func (m *TestMessage) GetMyData() []byte {
	if m != nil {
		return m.MyData
	}
	return nil
}

type SubMessage struct {
	StringVal            string   `protobuf:"bytes,1,opt,name=string_val,json=stringVal,proto3" json:"string_val,omitempty"`
	IntVal               int32    `protobuf:"varint,2,opt,name=int_val,json=intVal,proto3" json:"int_val,omitempty"`
	Int64Val             int64    `protobuf:"varint,3,opt,name=int64_val,json=int64Val,proto3" json:"int64_val,omitempty"`
	Huebr                []byte   `protobuf:"bytes,4,opt,name=huebr,proto3" json:"huebr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubMessage) Reset()         { *m = SubMessage{} }
func (m *SubMessage) String() string { return proto.CompactTextString(m) }
func (*SubMessage) ProtoMessage()    {}
func (*SubMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_2141552de9bf11d0, []int{1}
}

func (m *SubMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubMessage.Unmarshal(m, b)
}
func (m *SubMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubMessage.Marshal(b, m, deterministic)
}
func (m *SubMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubMessage.Merge(m, src)
}
func (m *SubMessage) XXX_Size() int {
	return xxx_messageInfo_SubMessage.Size(m)
}
func (m *SubMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SubMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SubMessage proto.InternalMessageInfo

func (m *SubMessage) GetStringVal() string {
	if m != nil {
		return m.StringVal
	}
	return ""
}

func (m *SubMessage) GetIntVal() int32 {
	if m != nil {
		return m.IntVal
	}
	return 0
}

func (m *SubMessage) GetInt64Val() int64 {
	if m != nil {
		return m.Int64Val
	}
	return 0
}

func (m *SubMessage) GetHuebr() []byte {
	if m != nil {
		return m.Huebr
	}
	return nil
}

func init() {
	proto.RegisterType((*TestMessage)(nil), "sample.TestMessage")
	proto.RegisterType((*SubMessage)(nil), "sample.SubMessage")
}

func init() {
	proto.RegisterFile("sample.proto", fileDescriptor_2141552de9bf11d0)
}

var fileDescriptor_2141552de9bf11d0 = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8f, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0x89, 0x6b, 0xe3, 0x66, 0x76, 0x4f, 0x61, 0xc1, 0x82, 0x08, 0x65, 0x4f, 0x3d, 0xad,
	0xa0, 0xe2, 0x2f, 0xf0, 0xea, 0x25, 0x4a, 0xaf, 0x65, 0x82, 0xa1, 0x06, 0x9a, 0xb4, 0x34, 0x13,
	0xa5, 0xff, 0x5e, 0x92, 0x14, 0xf6, 0xf8, 0xe6, 0xe3, 0xbd, 0x8f, 0x81, 0x63, 0x40, 0x37, 0x8f,
	0xe6, 0x32, 0x2f, 0x13, 0x4d, 0x92, 0x97, 0x74, 0x76, 0x70, 0xf8, 0x32, 0x81, 0x3e, 0x4c, 0x08,
	0x38, 0x18, 0x79, 0x82, 0xea, 0x17, 0xc7, 0x68, 0x6a, 0xd6, 0xb0, 0x56, 0xa8, 0x12, 0xe4, 0x13,
	0x88, 0x10, 0x75, 0x5f, 0xc8, 0x4d, 0xc3, 0xda, 0xc3, 0xb3, 0xbc, 0x6c, 0x73, 0x9f, 0x51, 0x6f,
	0x65, 0xb5, 0x0f, 0x51, 0x77, 0xb9, 0x70, 0x0f, 0x77, 0x6e, 0xed, 0xbf, 0x91, 0xb0, 0xde, 0x35,
	0xac, 0x3d, 0x2a, 0xee, 0xd6, 0x77, 0x24, 0x3c, 0xff, 0x01, 0x5c, 0x0b, 0xf2, 0x11, 0x20, 0xd0,
	0x62, 0xfd, 0x90, 0xa6, 0x37, 0xa5, 0x28, 0x97, 0x0e, 0xc7, 0xb4, 0x62, 0x3d, 0x65, 0x96, 0xa4,
	0x95, 0xe2, 0xd6, 0x53, 0x02, 0x0f, 0x20, 0xac, 0xa7, 0xb7, 0xd7, 0x8c, 0x92, 0x60, 0xa7, 0xf6,
	0xf9, 0x90, 0xe0, 0x09, 0xaa, 0x9f, 0x68, 0xf4, 0x52, 0xdf, 0x66, 0x73, 0x09, 0x9a, 0xe7, 0xb7,
	0x5f, 0xfe, 0x03, 0x00, 0x00, 0xff, 0xff, 0xc8, 0xd8, 0xb1, 0x35, 0x06, 0x01, 0x00, 0x00,
}
