// Code generated by protoc-gen-go. DO NOT EDIT.
// source: crypto.proto

package internal

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// EncryptedField is a ProtoCrypt Encrypted field entry
type EncryptedField struct {
	OriginalType         uint32   `protobuf:"varint,1,opt,name=original_type,json=originalType,proto3" json:"original_type,omitempty"`
	Nonce                []byte   `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Content              []byte   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EncryptedField) Reset()         { *m = EncryptedField{} }
func (m *EncryptedField) String() string { return proto.CompactTextString(m) }
func (*EncryptedField) ProtoMessage()    {}
func (*EncryptedField) Descriptor() ([]byte, []int) {
	return fileDescriptor_527278fb02d03321, []int{0}
}

func (m *EncryptedField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EncryptedField.Unmarshal(m, b)
}
func (m *EncryptedField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EncryptedField.Marshal(b, m, deterministic)
}
func (m *EncryptedField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EncryptedField.Merge(m, src)
}
func (m *EncryptedField) XXX_Size() int {
	return xxx_messageInfo_EncryptedField.Size(m)
}
func (m *EncryptedField) XXX_DiscardUnknown() {
	xxx_messageInfo_EncryptedField.DiscardUnknown(m)
}

var xxx_messageInfo_EncryptedField proto.InternalMessageInfo

func (m *EncryptedField) GetOriginalType() uint32 {
	if m != nil {
		return m.OriginalType
	}
	return 0
}

func (m *EncryptedField) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *EncryptedField) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func init() {
	proto.RegisterType((*EncryptedField)(nil), "protocrypt.EncryptedField")
}

func init() {
	proto.RegisterFile("crypto.proto", fileDescriptor_527278fb02d03321)
}

var fileDescriptor_527278fb02d03321 = []byte{
	// 129 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0x2e, 0xaa, 0x2c,
	0x28, 0xc9, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x02, 0x53, 0x60, 0x21, 0xa5, 0x54,
	0x2e, 0x3e, 0xd7, 0x3c, 0x30, 0x33, 0x35, 0xc5, 0x2d, 0x33, 0x35, 0x27, 0x45, 0x48, 0x99, 0x8b,
	0x37, 0xbf, 0x28, 0x33, 0x3d, 0x33, 0x2f, 0x31, 0x27, 0xbe, 0xa4, 0xb2, 0x20, 0x55, 0x82, 0x51,
	0x81, 0x51, 0x83, 0x37, 0x88, 0x07, 0x26, 0x18, 0x52, 0x59, 0x90, 0x2a, 0x24, 0xc2, 0xc5, 0x9a,
	0x97, 0x9f, 0x97, 0x9c, 0x2a, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x13, 0x04, 0xe1, 0x08, 0x49, 0x70,
	0xb1, 0x27, 0xe7, 0xe7, 0x95, 0xa4, 0xe6, 0x95, 0x48, 0x30, 0x83, 0xc5, 0x61, 0xdc, 0x24, 0x36,
	0xb0, 0x95, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb4, 0x53, 0x96, 0xbb, 0x89, 0x00, 0x00,
	0x00,
}
